// SPDX-License-Identifier: GPL-3.0-or-later
//
// GENERATED by wlrix-assets/tools/palettegen. Do not edit; edit the
// palette JSON in wlrix-assets/palette/ and re-run `just palette`.
//
// wlRIX Classic (gamma 1.7)
// Source: IRIX 6.5 X11 schemes: Base/BaseColorPalette, Base/ImdPalette, Base/HighlightPalette, Base/Base

// The palette is emitted whole; window chrome and other consumers land
// over time, so not every constant has a caller yet.
#![allow(dead_code)]

use smithay::backend::renderer::Color32F;

/// `#555555`
pub const DESKTOP: Color32F = Color32F::new(0.333333, 0.333333, 0.333333, 1.0);

/// `#000000`
pub const LOCKED: Color32F = Color32F::new(0.000000, 0.000000, 0.000000, 1.0);

/// `#a59f80`
pub const TITLE_ACTIVE: Color32F = Color32F::new(0.647059, 0.623529, 0.501961, 1.0);

/// `#000000`
pub const TITLE_ACTIVE_TEXT: Color32F = Color32F::new(0.000000, 0.000000, 0.000000, 1.0);

/// `#808080`
pub const TITLE_INACTIVE: Color32F = Color32F::new(0.501961, 0.501961, 0.501961, 1.0);

/// `#000000`
pub const TITLE_INACTIVE_TEXT: Color32F = Color32F::new(0.000000, 0.000000, 0.000000, 1.0);

/// `#c1c1c1`
pub const PANEL: Color32F = Color32F::new(0.756863, 0.756863, 0.756863, 1.0);

/// `#999999`
pub const FACE: Color32F = Color32F::new(0.600000, 0.600000, 0.600000, 1.0);

/// `#e5e5e5`
pub const TOP_SHADOW: Color32F = Color32F::new(0.898039, 0.898039, 0.898039, 1.0);

/// `#545454`
pub const BOTTOM_SHADOW: Color32F = Color32F::new(0.329412, 0.329412, 0.329412, 1.0);

/// `#000000`
pub const OUTER_LINE: Color32F = Color32F::new(0.000000, 0.000000, 0.000000, 1.0);

/// `#000000`
pub const FOREGROUND: Color32F = Color32F::new(0.000000, 0.000000, 0.000000, 1.0);
